### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by DrGo** [ssrg-vt/hermitux#1]
does/would it work on MacOS>

**Comment by olivierpierre** [comment]
Hello DrGo, unfortunately the answer is no. The hypervisor relies on the KVM interface to create and manage the virtual machine, therefore the host needs to run the Linux kernel.

**Comment by DrGo** [comment]
still great job! Thanks

**Comment by olivierpierre** [comment]
Thank you very much for your interest!
