### ISSUE TITLE
inconsistencies with gettimeofday()

### ISSUE THREAD

**Issue by p-jacquot** [ssrg-vt/hermitux#26]
For some machines, gettimeofday function seems to give inconsistent times.

On a [chiclet](https://www.grid5000.fr/w/Lille:Hardware#chiclet) node of g5k I have negative values for time intervals with Bots benchmarks (with [fft](https://github.com/ssrg-vt/hermitux/tree/master/apps/bots/fft) for example).
This bug does not occur every execution, you have to execute the program several times to see a negative value. It may be possible that sometimes, even a positive time interval could be wrong.

## Reproducing the bug :
Just executing fft with `make test` a few times on a chiclet node should be enough to see a negative time interval like this one : 
```
Time Program        = -0.827607 seconds
```

## Machine and cpu info

The chiclet node is equiped with an AMD EPYC 7301 (Zen, 2 CPUs/node, 16 cores/CPU).
I attached to this issue the content displayed by `lscpu` command : [chiclet-lscpu.txt](https://github.com/ssrg-vt/hermitux/files/6326095/chiclet-lscpu.txt)

Hyperthreading was disabled when I first experienced this bug, so I don't think it could be related to hyperthreading.

## source code related to the error

It seems that it is the use of `gettimeofday()` that cause this trouble.
Here is the function that get the time in the fft source code : 
```C
long bots_usecs (void)
{
   struct timeval t;
   gettimeofday(&t,NULL);
   return t.tv_sec*1000000+t.tv_usec;
}
```
You can find it [here](https://github.com/ssrg-vt/hermitux/blob/0f98c3c04e2db175731765197d4d74089f9920cc/apps/bots/fft/bots_common.c#L78).
The time duration is then computed by substracting a `end` with a `begin`. (you can find the computation [here](https://github.com/ssrg-vt/hermitux/blob/0f98c3c04e2db175731765197d4d74089f9920cc/apps/bots/fft/bots_main.c#L516))

I tried using `clock_gettime()` function to get time instead of `gettimeofday()`. By doing so I don't get inconsistent times anymore. So I think that the bug may be related to `gettimeofday()` implementation by Hermitux. Here is my workaround : [See my commit on my repo](https://github.com/p-jacquot/bots/commit/7c57d1cf9168356822fdd2ee270be4895f01f141)

**Comment by olivierpierre** [comment]
Fixed in this [commit](https://github.com/ssrg-vt/hermitux-kernel/commit/552c803aee27f144d4d6a388a425ad6197dc25fc)
