### ISSUE TITLE
Where is the uhyve resides？

### ISSUE THREAD

**Issue by a74731248** [ssrg-vt/hermitux#31]
hi! I am trying HermiTux with your [container](https://github.com/ssrg-vt/hermitux/wiki/Docker), and I have some confusions about uhyve.
1. where is the uhyve resides in this container? I can not find it with command `find / -name uhyve`.
2. Why can I use the command was described [there](https://github.com/hermitcore/uhyve#running-rustyhermit-apps-within-uhyve) it this container, and come with `uhyve: command not found`.
3. does the uhyve in this container compile from the one [that write with rust](https://github.com/hermitcore/uhyve)? or other? I remember you have mention in VEE'19' paper that uhyve have develop from ukvm to implement some new function, and I also want to learn about uhyve which was used in HermiTux, could you tell me where can I read the code of uhyve that was used in HermiTux?

**Comment by olivierpierre** [comment]
Hello!

1. I assume you refer to uhyve's binary, it's located in the container in `/root/hermitux/hermitux-kernel/prefix/bin/proxy`
2. The command you mention regards RustyHermit's version of uhyve, which is completely different from HermiTux'. Please see [here](https://github.com/ssrg-vt/hermitux#run-an-application) for examples of how to launch applications with HermiTux.
3. As mentioned above unfortunately HermiTux won't run as is with the rust version of uhyve (porting would probably require quite a bit of effort). You can find the sources of HermiTux' uhyve [here](https://github.com/ssrg-vt/hermitux-kernel/tree/master/tools), the main file being [`uhyve.c`](https://github.com/ssrg-vt/hermitux-kernel/blob/master/tools/uhyve.c)

I hope this helps!

**Comment by a74731248** [comment]
> thank you for reply, it help me a lot, and I still have some questions.
1. for the first point, do you mean that uhyve was intergrated into proxy? 
2. do all apps under directory `apps/` can run with qemu when I use the command like [here](https://github.com/ssrg-vt/hermitux#run-an-application) with `HERMIT_ISLE=qemu`? I have try this in `apps/npb/is`, and get stuck.

**Comment by a74731248** [comment]
> Hello!
> 
> 1. I assume you refer to uhyve's binary, it's located in the container in `/root/hermitux/hermitux-kernel/prefix/bin/proxy`
> 2. The command you mention regards RustyHermit's version of uhyve, which is completely different from HermiTux'. Please see [here](https://github.com/ssrg-vt/hermitux#run-an-application) for examples of how to launch applications with HermiTux.
> 3. As mentioned above unfortunately HermiTux won't run as is with the rust version of uhyve (porting would probably require quite a bit of effort). You can find the sources of HermiTux' uhyve [here](https://github.com/ssrg-vt/hermitux-kernel/tree/master/tools), the main file being [`uhyve.c`](https://github.com/ssrg-vt/hermitux-kernel/blob/master/tools/uhyve.c)
> 
> I hope this helps!

thank you for reply, it help me a lot, but I still have some questions there.
1. do you mean that uhyve was integrated into proxy?
2. do all apps under directory `apps/` can run with qemu when I use the command like [here](https://github.com/ssrg-vt/hermitux#run-an-application) with change `HERMIT_ISLE=qemu`? I have try the command below in `apps/npb/is`  but get stuck. 
```
HERMIT_ISLE=qemu HERMIT_TUX=1 \
	../../../hermitux-kernel/prefix/bin/proxy \
	../../../hermitux-kernel/prefix/x86_64-hermit/extra/tests/hermitux \
	/lib64/ld-linux-x86-64.so.2 ./is-dyn
```

**Comment by olivierpierre** [comment]
1. `proxy` is just the name of uhyve's binary. At some point I should probably rename it into something like `hermitux-uhyve` to be more explicit
2. Unfortunately HermiTux does not run with qemu, please see this [issue](https://github.com/ssrg-vt/hermitux/issues/2)

**Comment by a74731248** [comment]
when I read the `main` function in `tools/proxy.c`, I thought that proxy was a proxy that redirect to qemu or uhyve, thanks for explaining, and now I know what proxy was.
