### ISSUE TITLE
lmbench syscall latencies null vs. read/write

### ISSUE THREAD

**Issue by djwillia** [ssrg-vt/hermitux#6]
I've been trying out hermitux with the lmbench syscall latency example.  Specifically, I've been using the hermitux docker container with the `run-test.sh` script in the lmbench/lat_syscall directory.  Based on the hermitux VEE paper (figure 10), I expected null and read/write to be fairly similar in latency.  However, I see orders of magnitude differences (just the hermitux numbers):

null: 0.002547
read: 0.274750
write: 0.270750

Any ideas?

**Comment by olivierpierre** [comment]
Hello, I assume you did not enable MiniFS which is our toy internal filesystem. When not enabled, the filesystem calls such as `read()` or `write()` are forwarded to the host through an hypercall which is much more costly than processing them inside the unikernel with MiniFS. To use MiniFS simply activate it line 30 of our template Makefile:

```
MINIFS?=1
```

However, please note that MiniFS is very limited in terms of functionalities and does not scale well either.

**Comment by djwillia** [comment]
You are right, enabling MiniFS produced the expected results:

null: 0.002579
read: 0.003587
write: 0.003267

Thanks!
